name: Trigger testing pipeline

on:
  push:
    branches:
      - master
  pull_request:    
    branches: [master]    
    types: [opened, synchronize]  

jobs:
  testing_pipeline:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3 # Checkout the project source from Git
      - uses: actions/setup-node@v3 # Set up to be able to use commands specified in package.json
        with:
          node-version: '16'
      - name: Install dependencies # Install NodeJs dependencies
        run: npm install
      - name: Check style
        run: npm run eslint
      - name: Build 
        run: npm run build
      - name: Run tests
        run: npm run test
      - name: Run E2E tests
        uses: cypress-io/github-action@v5 # Use Cypress.io Github Action
        with:
          command: npm run test:e2e
          start: npm run start-prod
          wait-on: http://localhost:5000 # Before execute command, wait for start ecommand