name: Deployment papeline

on:
  push:
    branches:
      - master

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3 # Checkout the project source from Git
      - uses: actions/setup-node@v3 # Set up to be able to use commands specified in package.json
        with:
          node-version: '16'
      - name: Install dependencies # Install NodeJs dependencies
        run: npm install
      - name: Check style
        run: npm run eslint
      - name: Build 
        run: npm run build
      - name: Run tests
        run: npm run test